os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - FEATURES=
  - FEATURES=abi-7-9
matrix:
  allow_failures:
    - rust: nightly
  # Avoid excessive number of tests
  exclude:
    - rust: beta
      env: FEATURES=abi-7-9
    - rust: nightly
      env: FEATURES=abi-7-9
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update && sudo apt-get install -y libfuse-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew tap caskroom/cask && brew cask install osxfuse; fi
script:
  - cargo build --all --all-targets --features=$FEATURES
  - cargo test --all --features=$FEATURES
  - cargo doc --all --no-deps --features=$FEATURES
